"""First attempt

Revision ID: 787f3326a3d2
Revises: 17045a473e37
Create Date: 2024-06-02 18:10:41.261830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787f3326a3d2'
down_revision = '17045a473e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(length=100), nullable=True),
    sa.Column('artist_name', sa.String(length=100), nullable=True),
    sa.Column('artist_image_link', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venue_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('artist_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('artist_image_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='show_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='show_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='show_pkey')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###
